### ISSUE TITLE
Application failed due to an invalid Google Generative AI API key

### ISSUE THREAD

**Issue by 97revenge** [97revenge/gemini-getting-started#1]
```
ile:///var/task/node_modules/@google/generative-ai/dist/index.mjs:214:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (file:///var/task/node_modules/@google/generative-ai/dist/index.mjs:523:22)
    at async c (/var/task/.next/server/pages/api/create.js:6:9)
    at async K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:41752)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36452)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17030)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16123)
 ⨯ GoogleGenerativeAIError: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo"
,"reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]
    at makeRequest (file:///var/task/node_modules/@google/generative-ai/dist/index.mjs:214:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (file:///var/task/node_modules/@google/generative-ai/dist/index.mjs:523:22)
    at async c (/var/task/.next/server/pages/api/create.js:6:9)
    at async K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:41752)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36452)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17030)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16123)
GoogleGenerativeAIError: [400 Bad Request] API key not valid. Please pass a valid API key. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo",
"reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}}]
    at makeRequest (file:///var/task/node_modules/@google/generative-ai/dist/index.mjs:214:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (file:///var/task/node_modules/@google/generative-ai/dist/index.mjs:523:22)
    at async c (/var/task/.next/server/pages/api/create.js:6:9)
    at async K (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/var/task/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async r3.runApi (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:41752)
    at async r3.handleCatchallRenderRequest (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:36452)
    at async r3.runImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:17030)
    at async r3.handleRequestImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:16123)
Error: Runtime exited with error: exit status 1
Runtime.ExitError

``` 
![image](https://github.com/97revenge/gemini-getting-started/assets/80254945/f8898bd6-cc45-482e-b544-9b7ba4c06e71)

**Comment by 97revenge** [comment]
environment variables were added to the vercel platform and the problem was resolved

![image](https://github.com/97revenge/gemini-getting-started/assets/80254945/08949577-d8fa-4559-a8c2-2cd4954146bd)
